server:
  port: 39080

param:
  aaa: 99999999

spring:
  rabbitmq:
    host: 121.196.207.12
    port: 5672
    username: ddy
    password: ddy1111
    virtualHost: /
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.225.167:3306/uic2?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true
    username: uic
    password: uicisgood@999